language: cpp

os:
    - linux
    - osx
    
sudo : required

dist : trusty

compiler:
    - g++
    - clang++

matrix:
    exclude:
        - os: linux
          compiler: clang++

        - os: osx
          compiler: g++

#Build steps
before_install: 
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install sdl2_mixer sdl2_image sdl2_ttf ; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get udpate ; sudo apt-get install libsdl2-mixer-dev libsdl2-image-dev libsdl2-ttf-dev -y ; fi

script: if [ "$TRAVIS_OS_NAME" == "osx" ]; then make -f Makefile.macosx ; else make ; fi
