language: cpp

os:
    - linux
    - osx

dist : trusty

compiler:
    - g++
    - clang++

matrix:
    include:
        - os: linux
          sudo : required

    exclude:
        - os: linux
          compiler: clang++

        - os: osx
          compiler: g++

#Build steps
before_install: 
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install libsdl2-mixer libsdl2-image libsdl2-ttf ; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libsdl2-mixer-dev libsdl2-image-dev libsdl2-ttf-dev -y ; fi

script: if [ "$TRAVIS_OS_NAME" == "osx" ]; then make -f makefile.macosx ; else make ; fi